spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: mysqlpassword
  jpa:
    generate-ddl: true
    show-sql: true